from enum import StrEnum


class DataStorageEnum(StrEnum):
    CUBELIKE = "CUBELIKE"
    TABLE = "TABLE"
    DIMENSION_TEXTS = "DIMENSION_TEXTS"
    DIMENSION_ATTRIBUTES = "DIMENSION_ATTRIBUTES"
    DIMENSION_VALUES = "DIMENSION_VALUES"
    TABLE_REPLICATED = "TABLE_REPLICATED"
    CUBELIKE_REPLICATED = "CUBELIKE_REPLICATED"

    HIERARCHY_VERSIONS = "HIERARCHY_VERSIONS"
    HIERARCHY_TEXTVERSIONS = "HIERARCHY_TEXTVERSIONS"
    HIERARCHY_NODES = "HIERARCHY_NODES"
    HIERARCHY_TEXTNODES = "HIERARCHY_TEXTNODES"
