# coding: utf-8

# flake8: noqa
"""
    V1 Semantic layer API

    Semantic layer API for EPMPlatform

    The version of the OpenAPI document: 1.0.0
    Contact: abakin.a.v@sberbank.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from src.integrations.modelling_tools_api.codegen.models.aggregation_type import AggregationType
    from src.integrations.modelling_tools_api.codegen.models.ai_group import AiGroup
    from src.integrations.modelling_tools_api.codegen.models.ai_group_edit import AiGroupEdit
    from src.integrations.modelling_tools_api.codegen.models.ai_group_new import AiGroupNew
    from src.integrations.modelling_tools_api.codegen.models.ai_prompt import AiPrompt
    from src.integrations.modelling_tools_api.codegen.models.ai_prompt_analytic_descriptions import AiPromptAnalyticDescriptions
    from src.integrations.modelling_tools_api.codegen.models.any_field import AnyField
    from src.integrations.modelling_tools_api.codegen.models.composite_create import CompositeCreate
    from src.integrations.modelling_tools_api.codegen.models.composite_edit import CompositeEdit
    from src.integrations.modelling_tools_api.codegen.models.composite_edit_link_fields_inner import CompositeEditLinkFieldsInner
    from src.integrations.modelling_tools_api.codegen.models.composite_field import CompositeField
    from src.integrations.modelling_tools_api.codegen.models.composite_get import CompositeGet
    from src.integrations.modelling_tools_api.codegen.models.composite_version import CompositeVersion
    from src.integrations.modelling_tools_api.codegen.models.composite_version_all_of_link_fields import CompositeVersionAllOfLinkFields
    from src.integrations.modelling_tools_api.codegen.models.connection import Connection
    from src.integrations.modelling_tools_api.codegen.models.data_storage import DataStorage
    from src.integrations.modelling_tools_api.codegen.models.data_storage_create import DataStorageCreate
    from src.integrations.modelling_tools_api.codegen.models.data_storage_edit import DataStorageEdit
    from src.integrations.modelling_tools_api.codegen.models.data_storage_field import DataStorageField
    from src.integrations.modelling_tools_api.codegen.models.data_storage_type import DataStorageType
    from src.integrations.modelling_tools_api.codegen.models.data_storage_version import DataStorageVersion
    from src.integrations.modelling_tools_api.codegen.models.database import Database
    from src.integrations.modelling_tools_api.codegen.models.database_create import DatabaseCreate
    from src.integrations.modelling_tools_api.codegen.models.database_edit import DatabaseEdit
    from src.integrations.modelling_tools_api.codegen.models.datasource import Datasource
    from src.integrations.modelling_tools_api.codegen.models.db_object import DbObject
    from src.integrations.modelling_tools_api.codegen.models.db_object_for_search import DbObjectForSearch
    from src.integrations.modelling_tools_api.codegen.models.deleted import Deleted
    from src.integrations.modelling_tools_api.codegen.models.dimension import Dimension
    from src.integrations.modelling_tools_api.codegen.models.dimension_attribute import DimensionAttribute
    from src.integrations.modelling_tools_api.codegen.models.dimension_create import DimensionCreate
    from src.integrations.modelling_tools_api.codegen.models.dimension_edit import DimensionEdit
    from src.integrations.modelling_tools_api.codegen.models.dimension_filter import DimensionFilter
    from src.integrations.modelling_tools_api.codegen.models.dimension_key_type import DimensionKeyType
    from src.integrations.modelling_tools_api.codegen.models.dimension_version import DimensionVersion
    from src.integrations.modelling_tools_api.codegen.models.error import Error
    from src.integrations.modelling_tools_api.codegen.models.general_status import GeneralStatus
    from src.integrations.modelling_tools_api.codegen.models.get_a_model_version_by_model_name_and_tenant_name_and_version_id200_response import GetAModelVersionByModelNameAndTenantNameAndVersionId200Response
    from src.integrations.modelling_tools_api.codegen.models.get_ai_group_version_by_tenant_name_and_ai_group_id_and_version_id200_response import GetAiGroupVersionByTenantNameAndAiGroupIdAndVersionId200Response
    from src.integrations.modelling_tools_api.codegen.models.get_composite_version_by_model_name_and_dimension_name200_response import GetCompositeVersionByModelNameAndDimensionName200Response
    from src.integrations.modelling_tools_api.codegen.models.get_data_storage_version_by_model_name_and_dimension_name200_response import GetDataStorageVersionByModelNameAndDimensionName200Response
    from src.integrations.modelling_tools_api.codegen.models.get_database_version_by_model_name_and_database_name_and_version_id200_response import GetDatabaseVersionByModelNameAndDatabaseNameAndVersionId200Response
    from src.integrations.modelling_tools_api.codegen.models.get_dimension_version_by_model_name_and_dimension_name200_response import GetDimensionVersionByModelNameAndDimensionName200Response
    from src.integrations.modelling_tools_api.codegen.models.get_hierarchy_version_by_model_name_and_dimension_name200_response import GetHierarchyVersionByModelNameAndDimensionName200Response
    from src.integrations.modelling_tools_api.codegen.models.get_measure_version_by_model_name_and_dimension_name200_response import GetMeasureVersionByModelNameAndDimensionName200Response
    from src.integrations.modelling_tools_api.codegen.models.get_values200_response import GetValues200Response
    from src.integrations.modelling_tools_api.codegen.models.hierarchy import Hierarchy
    from src.integrations.modelling_tools_api.codegen.models.hierarchy_create import HierarchyCreate
    from src.integrations.modelling_tools_api.codegen.models.hierarchy_edit import HierarchyEdit
    from src.integrations.modelling_tools_api.codegen.models.hierarchy_version import HierarchyVersion
    from src.integrations.modelling_tools_api.codegen.models.hierarchy_version_all_of_data_storages import HierarchyVersionAllOfDataStorages
    from src.integrations.modelling_tools_api.codegen.models.http_validation_error import HttpValidationError
    from src.integrations.modelling_tools_api.codegen.models.http_validation_error_detail_inner import HttpValidationErrorDetailInner
    from src.integrations.modelling_tools_api.codegen.models.information_category import InformationCategory
    from src.integrations.modelling_tools_api.codegen.models.label_type import LabelType
    from src.integrations.modelling_tools_api.codegen.models.link_field import LinkField
    from src.integrations.modelling_tools_api.codegen.models.measure import Measure
    from src.integrations.modelling_tools_api.codegen.models.measure_create import MeasureCreate
    from src.integrations.modelling_tools_api.codegen.models.measure_edit import MeasureEdit
    from src.integrations.modelling_tools_api.codegen.models.measure_edit_unit_of_measure import MeasureEditUnitOfMeasure
    from src.integrations.modelling_tools_api.codegen.models.measure_key_type import MeasureKeyType
    from src.integrations.modelling_tools_api.codegen.models.measure_version import MeasureVersion
    from src.integrations.modelling_tools_api.codegen.models.model import Model
    from src.integrations.modelling_tools_api.codegen.models.model_create import ModelCreate
    from src.integrations.modelling_tools_api.codegen.models.model_edit import ModelEdit
    from src.integrations.modelling_tools_api.codegen.models.model_status import ModelStatus
    from src.integrations.modelling_tools_api.codegen.models.object_field_type import ObjectFieldType
    from src.integrations.modelling_tools_api.codegen.models.object_field_type_ref_object import ObjectFieldTypeRefObject
    from src.integrations.modelling_tools_api.codegen.models.object_labels_inner import ObjectLabelsInner
    from src.integrations.modelling_tools_api.codegen.models.object_links import ObjectLinks
    from src.integrations.modelling_tools_api.codegen.models.object_status import ObjectStatus
    from src.integrations.modelling_tools_api.codegen.models.object_type import ObjectType
    from src.integrations.modelling_tools_api.codegen.models.pagination import Pagination
    from src.integrations.modelling_tools_api.codegen.models.port import Port
    from src.integrations.modelling_tools_api.codegen.models.pv_dictionary import PvDictionary
    from src.integrations.modelling_tools_api.codegen.models.request_copy_object import RequestCopyObject
    from src.integrations.modelling_tools_api.codegen.models.request_copy_storage import RequestCopyStorage
    from src.integrations.modelling_tools_api.codegen.models.resp_copy_object_inner import RespCopyObjectInner
    from src.integrations.modelling_tools_api.codegen.models.resp_copy_storage_inner import RespCopyStorageInner
    from src.integrations.modelling_tools_api.codegen.models.resp_object_status import RespObjectStatus
    from src.integrations.modelling_tools_api.codegen.models.result import Result
    from src.integrations.modelling_tools_api.codegen.models.seacrh_group_items import SeacrhGroupItems
    from src.integrations.modelling_tools_api.codegen.models.search_response import SearchResponse
    from src.integrations.modelling_tools_api.codegen.models.search_type import SearchType
    from src.integrations.modelling_tools_api.codegen.models.semantic_type import SemanticType
    from src.integrations.modelling_tools_api.codegen.models.sort_direction import SortDirection
    from src.integrations.modelling_tools_api.codegen.models.specific_attribute import SpecificAttribute
    from src.integrations.modelling_tools_api.codegen.models.synchronization_result import SynchronizationResult
    from src.integrations.modelling_tools_api.codegen.models.tenant import Tenant
    from src.integrations.modelling_tools_api.codegen.models.tenant_edit import TenantEdit
    from src.integrations.modelling_tools_api.codegen.models.value_text import ValueText
    from src.integrations.modelling_tools_api.codegen.models.values_dimension_response import ValuesDimensionResponse
    from src.integrations.modelling_tools_api.codegen.models.values_dimension_response_texts_inner import ValuesDimensionResponseTextsInner
    from src.integrations.modelling_tools_api.codegen.models.values_filters_request import ValuesFiltersRequest
    from src.integrations.modelling_tools_api.codegen.models.values_filters_request_control_date_or_period import ValuesFiltersRequestControlDateOrPeriod
    from src.integrations.modelling_tools_api.codegen.models.values_filters_request_control_date_or_period_one_of import ValuesFiltersRequestControlDateOrPeriodOneOf
    from src.integrations.modelling_tools_api.codegen.models.version_info import VersionInfo
    from src.integrations.modelling_tools_api.codegen.models.versions_ai_inner import VersionsAiInner
    from src.integrations.modelling_tools_api.codegen.models.versions_inner import VersionsInner
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from src.integrations.modelling_tools_api.codegen.models.aggregation_type import AggregationType
from src.integrations.modelling_tools_api.codegen.models.ai_group import AiGroup
from src.integrations.modelling_tools_api.codegen.models.ai_group_edit import AiGroupEdit
from src.integrations.modelling_tools_api.codegen.models.ai_group_new import AiGroupNew
from src.integrations.modelling_tools_api.codegen.models.ai_prompt import AiPrompt
from src.integrations.modelling_tools_api.codegen.models.ai_prompt_analytic_descriptions import AiPromptAnalyticDescriptions
from src.integrations.modelling_tools_api.codegen.models.any_field import AnyField
from src.integrations.modelling_tools_api.codegen.models.composite_create import CompositeCreate
from src.integrations.modelling_tools_api.codegen.models.composite_edit import CompositeEdit
from src.integrations.modelling_tools_api.codegen.models.composite_edit_link_fields_inner import CompositeEditLinkFieldsInner
from src.integrations.modelling_tools_api.codegen.models.composite_field import CompositeField
from src.integrations.modelling_tools_api.codegen.models.composite_get import CompositeGet
from src.integrations.modelling_tools_api.codegen.models.composite_version import CompositeVersion
from src.integrations.modelling_tools_api.codegen.models.composite_version_all_of_link_fields import CompositeVersionAllOfLinkFields
from src.integrations.modelling_tools_api.codegen.models.connection import Connection
from src.integrations.modelling_tools_api.codegen.models.data_storage import DataStorage
from src.integrations.modelling_tools_api.codegen.models.data_storage_create import DataStorageCreate
from src.integrations.modelling_tools_api.codegen.models.data_storage_edit import DataStorageEdit
from src.integrations.modelling_tools_api.codegen.models.data_storage_field import DataStorageField
from src.integrations.modelling_tools_api.codegen.models.data_storage_type import DataStorageType
from src.integrations.modelling_tools_api.codegen.models.data_storage_version import DataStorageVersion
from src.integrations.modelling_tools_api.codegen.models.database import Database
from src.integrations.modelling_tools_api.codegen.models.database_create import DatabaseCreate
from src.integrations.modelling_tools_api.codegen.models.database_edit import DatabaseEdit
from src.integrations.modelling_tools_api.codegen.models.datasource import Datasource
from src.integrations.modelling_tools_api.codegen.models.db_object import DbObject
from src.integrations.modelling_tools_api.codegen.models.db_object_for_search import DbObjectForSearch
from src.integrations.modelling_tools_api.codegen.models.deleted import Deleted
from src.integrations.modelling_tools_api.codegen.models.dimension import Dimension
from src.integrations.modelling_tools_api.codegen.models.dimension_attribute import DimensionAttribute
from src.integrations.modelling_tools_api.codegen.models.dimension_create import DimensionCreate
from src.integrations.modelling_tools_api.codegen.models.dimension_edit import DimensionEdit
from src.integrations.modelling_tools_api.codegen.models.dimension_filter import DimensionFilter
from src.integrations.modelling_tools_api.codegen.models.dimension_key_type import DimensionKeyType
from src.integrations.modelling_tools_api.codegen.models.dimension_version import DimensionVersion
from src.integrations.modelling_tools_api.codegen.models.error import Error
from src.integrations.modelling_tools_api.codegen.models.general_status import GeneralStatus
from src.integrations.modelling_tools_api.codegen.models.get_a_model_version_by_model_name_and_tenant_name_and_version_id200_response import GetAModelVersionByModelNameAndTenantNameAndVersionId200Response
from src.integrations.modelling_tools_api.codegen.models.get_ai_group_version_by_tenant_name_and_ai_group_id_and_version_id200_response import GetAiGroupVersionByTenantNameAndAiGroupIdAndVersionId200Response
from src.integrations.modelling_tools_api.codegen.models.get_composite_version_by_model_name_and_dimension_name200_response import GetCompositeVersionByModelNameAndDimensionName200Response
from src.integrations.modelling_tools_api.codegen.models.get_data_storage_version_by_model_name_and_dimension_name200_response import GetDataStorageVersionByModelNameAndDimensionName200Response
from src.integrations.modelling_tools_api.codegen.models.get_database_version_by_model_name_and_database_name_and_version_id200_response import GetDatabaseVersionByModelNameAndDatabaseNameAndVersionId200Response
from src.integrations.modelling_tools_api.codegen.models.get_dimension_version_by_model_name_and_dimension_name200_response import GetDimensionVersionByModelNameAndDimensionName200Response
from src.integrations.modelling_tools_api.codegen.models.get_hierarchy_version_by_model_name_and_dimension_name200_response import GetHierarchyVersionByModelNameAndDimensionName200Response
from src.integrations.modelling_tools_api.codegen.models.get_measure_version_by_model_name_and_dimension_name200_response import GetMeasureVersionByModelNameAndDimensionName200Response
from src.integrations.modelling_tools_api.codegen.models.get_values200_response import GetValues200Response
from src.integrations.modelling_tools_api.codegen.models.hierarchy import Hierarchy
from src.integrations.modelling_tools_api.codegen.models.hierarchy_create import HierarchyCreate
from src.integrations.modelling_tools_api.codegen.models.hierarchy_edit import HierarchyEdit
from src.integrations.modelling_tools_api.codegen.models.hierarchy_version import HierarchyVersion
from src.integrations.modelling_tools_api.codegen.models.hierarchy_version_all_of_data_storages import HierarchyVersionAllOfDataStorages
from src.integrations.modelling_tools_api.codegen.models.http_validation_error import HttpValidationError
from src.integrations.modelling_tools_api.codegen.models.http_validation_error_detail_inner import HttpValidationErrorDetailInner
from src.integrations.modelling_tools_api.codegen.models.information_category import InformationCategory
from src.integrations.modelling_tools_api.codegen.models.label_type import LabelType
from src.integrations.modelling_tools_api.codegen.models.link_field import LinkField
from src.integrations.modelling_tools_api.codegen.models.measure import Measure
from src.integrations.modelling_tools_api.codegen.models.measure_create import MeasureCreate
from src.integrations.modelling_tools_api.codegen.models.measure_edit import MeasureEdit
from src.integrations.modelling_tools_api.codegen.models.measure_edit_unit_of_measure import MeasureEditUnitOfMeasure
from src.integrations.modelling_tools_api.codegen.models.measure_key_type import MeasureKeyType
from src.integrations.modelling_tools_api.codegen.models.measure_version import MeasureVersion
from src.integrations.modelling_tools_api.codegen.models.model import Model
from src.integrations.modelling_tools_api.codegen.models.model_create import ModelCreate
from src.integrations.modelling_tools_api.codegen.models.model_edit import ModelEdit
from src.integrations.modelling_tools_api.codegen.models.model_status import ModelStatus
from src.integrations.modelling_tools_api.codegen.models.object_field_type import ObjectFieldType
from src.integrations.modelling_tools_api.codegen.models.object_field_type_ref_object import ObjectFieldTypeRefObject
from src.integrations.modelling_tools_api.codegen.models.object_labels_inner import ObjectLabelsInner
from src.integrations.modelling_tools_api.codegen.models.object_links import ObjectLinks
from src.integrations.modelling_tools_api.codegen.models.object_status import ObjectStatus
from src.integrations.modelling_tools_api.codegen.models.object_type import ObjectType
from src.integrations.modelling_tools_api.codegen.models.pagination import Pagination
from src.integrations.modelling_tools_api.codegen.models.port import Port
from src.integrations.modelling_tools_api.codegen.models.pv_dictionary import PvDictionary
from src.integrations.modelling_tools_api.codegen.models.request_copy_object import RequestCopyObject
from src.integrations.modelling_tools_api.codegen.models.request_copy_storage import RequestCopyStorage
from src.integrations.modelling_tools_api.codegen.models.resp_copy_object_inner import RespCopyObjectInner
from src.integrations.modelling_tools_api.codegen.models.resp_copy_storage_inner import RespCopyStorageInner
from src.integrations.modelling_tools_api.codegen.models.resp_object_status import RespObjectStatus
from src.integrations.modelling_tools_api.codegen.models.result import Result
from src.integrations.modelling_tools_api.codegen.models.seacrh_group_items import SeacrhGroupItems
from src.integrations.modelling_tools_api.codegen.models.search_response import SearchResponse
from src.integrations.modelling_tools_api.codegen.models.search_type import SearchType
from src.integrations.modelling_tools_api.codegen.models.semantic_type import SemanticType
from src.integrations.modelling_tools_api.codegen.models.sort_direction import SortDirection
from src.integrations.modelling_tools_api.codegen.models.specific_attribute import SpecificAttribute
from src.integrations.modelling_tools_api.codegen.models.synchronization_result import SynchronizationResult
from src.integrations.modelling_tools_api.codegen.models.tenant import Tenant
from src.integrations.modelling_tools_api.codegen.models.tenant_edit import TenantEdit
from src.integrations.modelling_tools_api.codegen.models.value_text import ValueText
from src.integrations.modelling_tools_api.codegen.models.values_dimension_response import ValuesDimensionResponse
from src.integrations.modelling_tools_api.codegen.models.values_dimension_response_texts_inner import ValuesDimensionResponseTextsInner
from src.integrations.modelling_tools_api.codegen.models.values_filters_request import ValuesFiltersRequest
from src.integrations.modelling_tools_api.codegen.models.values_filters_request_control_date_or_period import ValuesFiltersRequestControlDateOrPeriod
from src.integrations.modelling_tools_api.codegen.models.values_filters_request_control_date_or_period_one_of import ValuesFiltersRequestControlDateOrPeriodOneOf
from src.integrations.modelling_tools_api.codegen.models.version_info import VersionInfo
from src.integrations.modelling_tools_api.codegen.models.versions_ai_inner import VersionsAiInner
from src.integrations.modelling_tools_api.codegen.models.versions_inner import VersionsInner

""",
            name=__name__,
            doc=__doc__,
        )
    )
