# coding: utf-8

"""
    V1 Semantic layer API

    Semantic layer API for EPMPlatform

    The version of the OpenAPI document: 1.0.0
    Contact: abakin.a.v@sberbank.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from src.integrations.modelling_tools_api.codegen.models.ai_group_edit import AiGroupEdit
from src.integrations.modelling_tools_api.codegen.models.ai_prompt_analytic_descriptions import AiPromptAnalyticDescriptions
from typing import Set
from typing_extensions import Self

class AiPrompt(BaseModel):
    """
    AiPrompt
    """ # noqa: E501
    analytic_role: Annotated[List[Annotated[str, Field(min_length=1, strict=True, max_length=8192)]], Field(min_length=0, max_length=100)] = Field(description="Роль в аналитике", alias="analyticRole")
    related_dimensions: Optional[Annotated[List[Annotated[str, Field(min_length=1, strict=True, max_length=32)]], Field(min_length=0, max_length=100)]] = Field(default=None, description="Список зависимых сущностей. Определяется как те измерения, атрибутами которого являются выбранные", alias="relatedDimensions")
    purpose: Annotated[List[Annotated[str, Field(min_length=1, strict=True, max_length=8192)]], Field(min_length=0, max_length=100)] = Field(description="Назначение")
    key_features: Annotated[List[Annotated[str, Field(min_length=1, strict=True, max_length=8192)]], Field(min_length=0, max_length=100)] = Field(description="Ключевые особенности", alias="keyFeatures")
    data_type: Annotated[List[Annotated[str, Field(min_length=1, strict=True, max_length=255)]], Field(min_length=0, max_length=100)] = Field(description="Тип данных", alias="dataType")
    subject_area: Annotated[List[Annotated[str, Field(min_length=1, strict=True, max_length=255)]], Field(min_length=0, max_length=100)] = Field(description="Предметная область", alias="subjectArea")
    example_questions: Annotated[List[Annotated[str, Field(min_length=1, strict=True, max_length=255)]], Field(min_length=0, max_length=100)] = Field(description="Вопросы для извлечения. Примеры вопросов для аналитики (анализ затрат, распределение расходов)", alias="exampleQuestions")
    markers: Annotated[List[Annotated[str, Field(min_length=1, strict=True, max_length=1024)]], Field(min_length=0, max_length=100)] = Field(description="Маркерные признаки")
    notes: Annotated[List[Annotated[str, Field(min_length=1, strict=True, max_length=1024)]], Field(min_length=0, max_length=100)] = Field(description="Дополнительные примечания (описание сокращений, типов МВЗ)")
    ai_usage: StrictBool = Field(description="Флаг использования измерения / группы в AI", alias="aiUsage")
    domain_id: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=1)]] = Field(default=None, description="Отчет / область (для расширения функционала ассистента в Q4, выбор среди нескольких отчетов)", alias="domainId")
    group_id: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=1)]] = Field(default=None, description="Идентификатор группы, к которой принадлежит измерение", alias="groupId")
    vector_search: StrictBool = Field(description="Флаг присутствия в ВБД (можем искать значение аналитики и использовать в фильтре)", alias="vectorSearch")
    fallback_to_llm_values: StrictBool = Field(description="Флаг отката к значениям LLM", alias="fallbackToLlmValues")
    preferable_column: StrictBool = Field(description="Размещаем в столбце или в строке (default=false аналитика в столбец)", alias="preferableColumn")
    group_descriptions: Optional[AiGroupEdit] = Field(default=None, alias="groupDescriptions")
    analytic_descriptions: AiPromptAnalyticDescriptions = Field(alias="analyticDescriptions")
    __properties: ClassVar[List[str]] = ["analyticRole", "relatedDimensions", "purpose", "keyFeatures", "dataType", "subjectArea", "exampleQuestions", "markers", "notes", "aiUsage", "domainId", "groupId", "vectorSearch", "fallbackToLlmValues", "preferableColumn", "groupDescriptions", "analyticDescriptions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AiPrompt from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of group_descriptions
        if self.group_descriptions:
            _dict['groupDescriptions'] = self.group_descriptions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of analytic_descriptions
        if self.analytic_descriptions:
            _dict['analyticDescriptions'] = self.analytic_descriptions.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AiPrompt from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "analyticRole": obj.get("analyticRole"),
            "relatedDimensions": obj.get("relatedDimensions"),
            "purpose": obj.get("purpose"),
            "keyFeatures": obj.get("keyFeatures"),
            "dataType": obj.get("dataType"),
            "subjectArea": obj.get("subjectArea"),
            "exampleQuestions": obj.get("exampleQuestions"),
            "markers": obj.get("markers"),
            "notes": obj.get("notes"),
            "aiUsage": obj.get("aiUsage") if obj.get("aiUsage") is not None else False,
            "domainId": obj.get("domainId"),
            "groupId": obj.get("groupId"),
            "vectorSearch": obj.get("vectorSearch") if obj.get("vectorSearch") is not None else False,
            "fallbackToLlmValues": obj.get("fallbackToLlmValues") if obj.get("fallbackToLlmValues") is not None else False,
            "preferableColumn": obj.get("preferableColumn") if obj.get("preferableColumn") is not None else False,
            "groupDescriptions": AiGroupEdit.from_dict(obj["groupDescriptions"]) if obj.get("groupDescriptions") is not None else None,
            "analyticDescriptions": AiPromptAnalyticDescriptions.from_dict(obj["analyticDescriptions"]) if obj.get("analyticDescriptions") is not None else None
        })
        return _obj


