# coding: utf-8

"""
    V1 Semantic layer API

    Semantic layer API for EPMPlatform

    The version of the OpenAPI document: 1.0.0
    Contact: abakin.a.v@sberbank.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from src.integrations.modelling_tools_api.codegen.models.aggregation_type import AggregationType
from src.integrations.modelling_tools_api.codegen.models.object_labels_inner import ObjectLabelsInner
from typing import Set
from typing_extensions import Self

class AnyField(BaseModel):
    """
    AnyField
    """ # noqa: E501
    name: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=32)]] = Field(default=None, description="Уникальное техническое имя объекта")
    labels: Optional[Annotated[List[ObjectLabelsInner], Field(max_length=100)]] = Field(default=None, description="Тексты, которые описывают различные сущности системы на разных языках для   - признаков   - атрибутов признаков   - показателей   - хранилищ данных   - композитов   - ... ")
    type: Optional[Annotated[str, Field(strict=True, max_length=20)]] = Field(default=None, description="Технический тип данных поля (состоит из типов измерения и показателя)")
    aggregation_type: Optional[AggregationType] = Field(default=None, alias="aggregationType")
    precision: Optional[Annotated[int, Field(le=1333, strict=True, ge=1)]] = Field(default=None, description="Overall lenght of data")
    scale: Optional[Annotated[int, Field(le=34, strict=True, ge=0)]] = Field(default=None, description="Number of digits after fpoint")
    __properties: ClassVar[List[str]] = ["name", "labels", "type", "aggregationType", "precision", "scale"]

    @field_validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9_]+$/")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['INTEGER', 'STRING', 'DATE', 'TIME', 'DATETIME', 'TIMESTAMP', 'BOOLEAN', 'ARRAY[STRING]', 'FLOAT', 'DECIMAL', 'UUID', 'JSON', 'ARRAY[INTEGER]']):
            raise ValueError("must be one of enum values ('INTEGER', 'STRING', 'DATE', 'TIME', 'DATETIME', 'TIMESTAMP', 'BOOLEAN', 'ARRAY[STRING]', 'FLOAT', 'DECIMAL', 'UUID', 'JSON', 'ARRAY[INTEGER]')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnyField from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items = []
        if self.labels:
            for _item_labels in self.labels:
                if _item_labels:
                    _items.append(_item_labels.to_dict())
            _dict['labels'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnyField from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "labels": [ObjectLabelsInner.from_dict(_item) for _item in obj["labels"]] if obj.get("labels") is not None else None,
            "type": obj.get("type"),
            "aggregationType": obj.get("aggregationType"),
            "precision": obj.get("precision"),
            "scale": obj.get("scale")
        })
        return _obj


