# coding: utf-8

"""
    V1 Semantic layer API

    Semantic layer API for EPMPlatform

    The version of the OpenAPI document: 1.0.0
    Contact: abakin.a.v@sberbank.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from src.integrations.modelling_tools_api.codegen.models.composite_field import CompositeField
from src.integrations.modelling_tools_api.codegen.models.composite_version_all_of_link_fields import CompositeVersionAllOfLinkFields
from src.integrations.modelling_tools_api.codegen.models.datasource import Datasource
from src.integrations.modelling_tools_api.codegen.models.db_object import DbObject
from src.integrations.modelling_tools_api.codegen.models.general_status import GeneralStatus
from src.integrations.modelling_tools_api.codegen.models.information_category import InformationCategory
from src.integrations.modelling_tools_api.codegen.models.model_status import ModelStatus
from src.integrations.modelling_tools_api.codegen.models.object_labels_inner import ObjectLabelsInner
from typing import Set
from typing_extensions import Self

class CompositeVersion(BaseModel):
    """
    CompositeVersion
    """ # noqa: E501
    version: Optional[Annotated[int, Field(le=1333, strict=True)]] = None
    updated_at: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Дата и время", alias="updatedAt")
    updated_by: Optional[Annotated[str, Field(strict=True, max_length=8192)]] = Field(default=None, description="Пользователь", alias="updatedBy")
    status: Optional[GeneralStatus] = None
    name: Annotated[str, Field(min_length=1, strict=True, max_length=32)] = Field(description="Уникальное техническое имя объекта")
    schema_name: Annotated[str, Field(min_length=0, strict=True, max_length=255)] = Field(description="Имя схемы базы данных", alias="schemaName")
    information_category: Optional[InformationCategory] = Field(default=None, alias="informationCategory")
    labels: Optional[Annotated[List[ObjectLabelsInner], Field(max_length=100)]] = Field(default=None, description="Тексты, которые описывают различные сущности системы на разных языках для   - признаков   - атрибутов признаков   - показателей   - хранилищ данных   - композитов   - ... ")
    fields: Annotated[List[CompositeField], Field(min_length=1, max_length=1000)]
    db_objects: Optional[Annotated[List[DbObject], Field(min_length=0, max_length=10)]] = Field(default=None, description="Список объектов БД для data storage", alias="dbObjects")
    models: Optional[Annotated[List[ModelStatus], Field(max_length=1000)]] = Field(default=None, description="Модели, использующие композит, со статусом обработки объекта в нем")
    fbp: Optional[Annotated[List[Annotated[str, Field(min_length=0, strict=True, max_length=10)]], Field(max_length=1000)]] = None
    datasources: Annotated[List[Datasource], Field(min_length=1, max_length=1000)] = Field(description="Источники данных в композите")
    link_fields: Optional[Annotated[List[CompositeVersionAllOfLinkFields], Field(max_length=1000)]] = Field(default=None, description="Список полей композита, участвующих в JOIN", alias="linkFields")
    link_type: StrictStr = Field(description="Тип связи источников данных", alias="linkType")
    __properties: ClassVar[List[str]] = ["version", "updatedAt", "updatedBy", "status", "name", "schemaName", "informationCategory", "labels", "fields", "dbObjects", "models", "fbp", "datasources", "linkFields", "linkType"]

    @field_validator('updated_at')
    def updated_at_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\n\t]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\n\t]+$/")
        return value

    @field_validator('updated_by')
    def updated_by_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\n\t]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\n\t]+$/")
        return value

    @field_validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9_]+$/")
        return value

    @field_validator('schema_name')
    def schema_name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-zA-Z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z0-9_]+$/")
        return value

    @field_validator('link_type')
    def link_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['LEFT_JOIN', 'INNER_JOIN', 'UNION', 'SELECT']):
            raise ValueError("must be one of enum values ('LEFT_JOIN', 'INNER_JOIN', 'UNION', 'SELECT')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CompositeVersion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items = []
        if self.labels:
            for _item_labels in self.labels:
                if _item_labels:
                    _items.append(_item_labels.to_dict())
            _dict['labels'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in fields (list)
        _items = []
        if self.fields:
            for _item_fields in self.fields:
                if _item_fields:
                    _items.append(_item_fields.to_dict())
            _dict['fields'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in db_objects (list)
        _items = []
        if self.db_objects:
            for _item_db_objects in self.db_objects:
                if _item_db_objects:
                    _items.append(_item_db_objects.to_dict())
            _dict['dbObjects'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in models (list)
        _items = []
        if self.models:
            for _item_models in self.models:
                if _item_models:
                    _items.append(_item_models.to_dict())
            _dict['models'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in datasources (list)
        _items = []
        if self.datasources:
            for _item_datasources in self.datasources:
                if _item_datasources:
                    _items.append(_item_datasources.to_dict())
            _dict['datasources'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in link_fields (list)
        _items = []
        if self.link_fields:
            for _item_link_fields in self.link_fields:
                if _item_link_fields:
                    _items.append(_item_link_fields.to_dict())
            _dict['linkFields'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CompositeVersion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "version": obj.get("version"),
            "updatedAt": obj.get("updatedAt"),
            "updatedBy": obj.get("updatedBy"),
            "status": obj.get("status"),
            "name": obj.get("name"),
            "schemaName": obj.get("schemaName"),
            "informationCategory": obj.get("informationCategory"),
            "labels": [ObjectLabelsInner.from_dict(_item) for _item in obj["labels"]] if obj.get("labels") is not None else None,
            "fields": [CompositeField.from_dict(_item) for _item in obj["fields"]] if obj.get("fields") is not None else None,
            "dbObjects": [DbObject.from_dict(_item) for _item in obj["dbObjects"]] if obj.get("dbObjects") is not None else None,
            "models": [ModelStatus.from_dict(_item) for _item in obj["models"]] if obj.get("models") is not None else None,
            "fbp": obj.get("fbp"),
            "datasources": [Datasource.from_dict(_item) for _item in obj["datasources"]] if obj.get("datasources") is not None else None,
            "linkFields": [CompositeVersionAllOfLinkFields.from_dict(_item) for _item in obj["linkFields"]] if obj.get("linkFields") is not None else None,
            "linkType": obj.get("linkType")
        })
        return _obj


