# coding: utf-8

"""
    V1 Semantic layer API

    Semantic layer API for EPMPlatform

    The version of the OpenAPI document: 1.0.0
    Contact: abakin.a.v@sberbank.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from src.integrations.modelling_tools_api.codegen.models.composite_edit_link_fields_inner import CompositeEditLinkFieldsInner
from src.integrations.modelling_tools_api.codegen.models.composite_field import CompositeField
from src.integrations.modelling_tools_api.codegen.models.datasource import Datasource
from src.integrations.modelling_tools_api.codegen.models.information_category import InformationCategory
from src.integrations.modelling_tools_api.codegen.models.object_labels_inner import ObjectLabelsInner
from typing import Set
from typing_extensions import Self

class CompositeEdit(BaseModel):
    """
    CompositeEdit
    """ # noqa: E501
    information_category: Optional[InformationCategory] = Field(default=None, alias="informationCategory")
    labels: Optional[Annotated[List[ObjectLabelsInner], Field(max_length=100)]] = Field(default=None, description="Тексты, которые описывают различные сущности системы на разных языках для   - признаков   - атрибутов признаков   - показателей   - хранилищ данных   - композитов   - ... ")
    datasources: Optional[Annotated[List[Datasource], Field(min_length=1, max_length=1000)]] = Field(default=None, description="Источники данных в композите")
    fields: Optional[Annotated[List[CompositeField], Field(min_length=1, max_length=1000)]] = Field(default=None, description="Поля из источников данных в композите")
    link_type: Optional[StrictStr] = Field(default=None, description="Тип связи источников данных", alias="linkType")
    link_fields: Optional[Annotated[List[CompositeEditLinkFieldsInner], Field(max_length=1000)]] = Field(default=None, description="Список полей композита, участвующих в JOIN", alias="linkFields")
    __properties: ClassVar[List[str]] = ["informationCategory", "labels", "datasources", "fields", "linkType", "linkFields"]

    @field_validator('link_type')
    def link_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['LEFT_JOIN', 'INNER_JOIN', 'UNION', 'SELECT']):
            raise ValueError("must be one of enum values ('LEFT_JOIN', 'INNER_JOIN', 'UNION', 'SELECT')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CompositeEdit from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items = []
        if self.labels:
            for _item_labels in self.labels:
                if _item_labels:
                    _items.append(_item_labels.to_dict())
            _dict['labels'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in datasources (list)
        _items = []
        if self.datasources:
            for _item_datasources in self.datasources:
                if _item_datasources:
                    _items.append(_item_datasources.to_dict())
            _dict['datasources'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in fields (list)
        _items = []
        if self.fields:
            for _item_fields in self.fields:
                if _item_fields:
                    _items.append(_item_fields.to_dict())
            _dict['fields'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in link_fields (list)
        _items = []
        if self.link_fields:
            for _item_link_fields in self.link_fields:
                if _item_link_fields:
                    _items.append(_item_link_fields.to_dict())
            _dict['linkFields'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CompositeEdit from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "informationCategory": obj.get("informationCategory"),
            "labels": [ObjectLabelsInner.from_dict(_item) for _item in obj["labels"]] if obj.get("labels") is not None else None,
            "datasources": [Datasource.from_dict(_item) for _item in obj["datasources"]] if obj.get("datasources") is not None else None,
            "fields": [CompositeField.from_dict(_item) for _item in obj["fields"]] if obj.get("fields") is not None else None,
            "linkType": obj.get("linkType"),
            "linkFields": [CompositeEditLinkFieldsInner.from_dict(_item) for _item in obj["linkFields"]] if obj.get("linkFields") is not None else None
        })
        return _obj


