# coding: utf-8

"""
    V1 Semantic layer API

    Semantic layer API for EPMPlatform

    The version of the OpenAPI document: 1.0.0
    Contact: abakin.a.v@sberbank.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from src.integrations.modelling_tools_api.codegen.models.data_storage_field import DataStorageField
from src.integrations.modelling_tools_api.codegen.models.data_storage_type import DataStorageType
from src.integrations.modelling_tools_api.codegen.models.db_object import DbObject
from src.integrations.modelling_tools_api.codegen.models.information_category import InformationCategory
from src.integrations.modelling_tools_api.codegen.models.object_labels_inner import ObjectLabelsInner
from typing import Set
from typing_extensions import Self

class DataStorageEdit(BaseModel):
    """
    DataStorageEdit
    """ # noqa: E501
    information_category: Optional[InformationCategory] = Field(default=None, alias="informationCategory")
    labels: Optional[Annotated[List[ObjectLabelsInner], Field(max_length=100)]] = Field(default=None, description="Тексты, которые описывают различные сущности системы на разных языках для   - признаков   - атрибутов признаков   - показателей   - хранилищ данных   - композитов   - ... ")
    type: Optional[DataStorageType] = None
    planning_enabled: Optional[StrictBool] = Field(default=False, description="Возможность изменения данных в DSO", alias="planningEnabled")
    log_data_storage_name: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = Field(default=None, description="Уникальное техническое имя объекта", alias="logDataStorageName")
    db_objects: Optional[Annotated[List[DbObject], Field(min_length=1, max_length=10)]] = Field(default=None, description="Список объектов БД для data storage", alias="dbObjects")
    fields: Optional[Annotated[List[DataStorageField], Field(min_length=1, max_length=1000)]] = Field(default=None, description="Список полей в data storage")
    __properties: ClassVar[List[str]] = ["informationCategory", "labels", "type", "planningEnabled", "logDataStorageName", "dbObjects", "fields"]

    @field_validator('log_data_storage_name')
    def log_data_storage_name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9_]+$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DataStorageEdit from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items = []
        if self.labels:
            for _item_labels in self.labels:
                if _item_labels:
                    _items.append(_item_labels.to_dict())
            _dict['labels'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in db_objects (list)
        _items = []
        if self.db_objects:
            for _item_db_objects in self.db_objects:
                if _item_db_objects:
                    _items.append(_item_db_objects.to_dict())
            _dict['dbObjects'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in fields (list)
        _items = []
        if self.fields:
            for _item_fields in self.fields:
                if _item_fields:
                    _items.append(_item_fields.to_dict())
            _dict['fields'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DataStorageEdit from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "informationCategory": obj.get("informationCategory"),
            "labels": [ObjectLabelsInner.from_dict(_item) for _item in obj["labels"]] if obj.get("labels") is not None else None,
            "type": obj.get("type"),
            "planningEnabled": obj.get("planningEnabled") if obj.get("planningEnabled") is not None else False,
            "logDataStorageName": obj.get("logDataStorageName"),
            "dbObjects": [DbObject.from_dict(_item) for _item in obj["dbObjects"]] if obj.get("dbObjects") is not None else None,
            "fields": [DataStorageField.from_dict(_item) for _item in obj["fields"]] if obj.get("fields") is not None else None
        })
        return _obj


