# coding: utf-8

"""
    V1 Semantic layer API

    Semantic layer API for EPMPlatform

    The version of the OpenAPI document: 1.0.0
    Contact: abakin.a.v@sberbank.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DataStorageType(str, Enum):
    """
    Тип хранилища
    """

    """
    allowed enum values
    """
    CUBELIKE = 'CUBELIKE'
    TABLE = 'TABLE'
    DIMENSION_VALUES = 'DIMENSION_VALUES'
    DIMENSION_TEXTS = 'DIMENSION_TEXTS'
    DIMENSION_ATTRIBUTES = 'DIMENSION_ATTRIBUTES'
    HIERARCHY_VERSIONS = 'HIERARCHY_VERSIONS'
    HIERARCHY_TEXTVERSIONS = 'HIERARCHY_TEXTVERSIONS'
    HIERARCHY_NODES = 'HIERARCHY_NODES'
    HIERARCHY_TEXTNODES = 'HIERARCHY_TEXTNODES'
    CUBELIKE_REPLICATED = 'CUBELIKE_REPLICATED'
    TABLE_REPLICATED = 'TABLE_REPLICATED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DataStorageType from a JSON string"""
        return cls(json.loads(json_str))


