# coding: utf-8

"""
    V1 Semantic layer API

    Semantic layer API for EPMPlatform

    The version of the OpenAPI document: 1.0.0
    Contact: abakin.a.v@sberbank.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from src.integrations.modelling_tools_api.codegen.models.ai_prompt import AiPrompt
from src.integrations.modelling_tools_api.codegen.models.dimension_attribute import DimensionAttribute
from src.integrations.modelling_tools_api.codegen.models.dimension_key_type import DimensionKeyType
from src.integrations.modelling_tools_api.codegen.models.information_category import InformationCategory
from src.integrations.modelling_tools_api.codegen.models.object_labels_inner import ObjectLabelsInner
from src.integrations.modelling_tools_api.codegen.models.value_text import ValueText
from typing import Set
from typing_extensions import Self

class DimensionEdit(BaseModel):
    """
    DimensionEdit
    """ # noqa: E501
    information_category: Optional[InformationCategory] = Field(default=None, alias="informationCategory")
    labels: Optional[Annotated[List[ObjectLabelsInner], Field(max_length=100)]] = Field(default=None, description="Тексты, которые описывают различные сущности системы на разных языках для   - признаков   - атрибутов признаков   - показателей   - хранилищ данных   - композитов   - ... ")
    precision: Optional[Annotated[int, Field(le=1333, strict=True, ge=1)]] = Field(default=None, description="Длина поля")
    type: Optional[DimensionKeyType] = None
    authorization_relevant: Optional[StrictBool] = Field(default=False, description="Релевантность проверке полномочий", alias="authorizationRelevant")
    texts_time_dependency: Optional[StrictBool] = Field(default=False, description="Зависимость текстов от времени", alias="textsTimeDependency")
    texts_language_dependency: Optional[StrictBool] = Field(default=False, description="Зависимость текстов от языка", alias="textsLanguageDependency")
    dimension_ref: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=32)]] = Field(default=None, description="Уникальное техническое имя объекта", alias="dimensionRef")
    value_texts: Optional[Annotated[List[ValueText], Field(max_length=10)]] = Field(default=None, alias="valueTexts")
    value_attributes: Optional[Annotated[List[DimensionAttribute], Field(max_length=1000)]] = Field(default=None, alias="valueAttributes")
    case_sensitive: Optional[StrictBool] = Field(default=False, description="Зависимость значений от регистра", alias="caseSensitive")
    data_access_method: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=255)]] = Field(default=None, description="Метод доступа к данным", alias="dataAccessMethod")
    business_key_representation: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=255)]] = Field(default=None, description="Отображение бизнес-ключа", alias="businessKeyRepresentation")
    is_virtual: Optional[StrictBool] = Field(default=False, description="Виртуальное измерение", alias="isVirtual")
    ai_prompt: Optional[AiPrompt] = Field(default=None, alias="aiPrompt")
    __properties: ClassVar[List[str]] = ["informationCategory", "labels", "precision", "type", "authorizationRelevant", "textsTimeDependency", "textsLanguageDependency", "dimensionRef", "valueTexts", "valueAttributes", "caseSensitive", "dataAccessMethod", "businessKeyRepresentation", "isVirtual", "aiPrompt"]

    @field_validator('dimension_ref')
    def dimension_ref_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9_]+$/")
        return value

    @field_validator('data_access_method')
    def data_access_method_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z0-9_]+$/")
        return value

    @field_validator('business_key_representation')
    def business_key_representation_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z0-9_]+$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DimensionEdit from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items = []
        if self.labels:
            for _item_labels in self.labels:
                if _item_labels:
                    _items.append(_item_labels.to_dict())
            _dict['labels'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in value_attributes (list)
        _items = []
        if self.value_attributes:
            for _item_value_attributes in self.value_attributes:
                if _item_value_attributes:
                    _items.append(_item_value_attributes.to_dict())
            _dict['valueAttributes'] = _items
        # override the default output from pydantic by calling `to_dict()` of ai_prompt
        if self.ai_prompt:
            _dict['aiPrompt'] = self.ai_prompt.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DimensionEdit from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "informationCategory": obj.get("informationCategory"),
            "labels": [ObjectLabelsInner.from_dict(_item) for _item in obj["labels"]] if obj.get("labels") is not None else None,
            "precision": obj.get("precision"),
            "type": obj.get("type"),
            "authorizationRelevant": obj.get("authorizationRelevant") if obj.get("authorizationRelevant") is not None else False,
            "textsTimeDependency": obj.get("textsTimeDependency") if obj.get("textsTimeDependency") is not None else False,
            "textsLanguageDependency": obj.get("textsLanguageDependency") if obj.get("textsLanguageDependency") is not None else False,
            "dimensionRef": obj.get("dimensionRef"),
            "valueTexts": obj.get("valueTexts"),
            "valueAttributes": [DimensionAttribute.from_dict(_item) for _item in obj["valueAttributes"]] if obj.get("valueAttributes") is not None else None,
            "caseSensitive": obj.get("caseSensitive") if obj.get("caseSensitive") is not None else False,
            "dataAccessMethod": obj.get("dataAccessMethod"),
            "businessKeyRepresentation": obj.get("businessKeyRepresentation"),
            "isVirtual": obj.get("isVirtual") if obj.get("isVirtual") is not None else False,
            "aiPrompt": AiPrompt.from_dict(obj["aiPrompt"]) if obj.get("aiPrompt") is not None else None
        })
        return _obj


