# coding: utf-8

"""
    V1 Semantic layer API

    Semantic layer API for EPMPlatform

    The version of the OpenAPI document: 1.0.0
    Contact: abakin.a.v@sberbank.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from src.integrations.modelling_tools_api.codegen.models.ai_prompt import AiPrompt
from src.integrations.modelling_tools_api.codegen.models.dimension_attribute import DimensionAttribute
from src.integrations.modelling_tools_api.codegen.models.dimension_key_type import DimensionKeyType
from src.integrations.modelling_tools_api.codegen.models.general_status import GeneralStatus
from src.integrations.modelling_tools_api.codegen.models.information_category import InformationCategory
from src.integrations.modelling_tools_api.codegen.models.model_status import ModelStatus
from src.integrations.modelling_tools_api.codegen.models.object_labels_inner import ObjectLabelsInner
from src.integrations.modelling_tools_api.codegen.models.pv_dictionary import PvDictionary
from src.integrations.modelling_tools_api.codegen.models.value_text import ValueText
from typing import Set
from typing_extensions import Self

class Dimension(BaseModel):
    """
    Dimension
    """ # noqa: E501
    version: Optional[Annotated[int, Field(le=1333, strict=True)]] = None
    updated_at: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Дата и время", alias="updatedAt")
    updated_by: Optional[Annotated[str, Field(strict=True, max_length=8192)]] = Field(default=None, description="Пользователь", alias="updatedBy")
    status: Optional[GeneralStatus] = None
    name: Annotated[str, Field(min_length=1, strict=True, max_length=32)] = Field(description="Уникальное техническое имя объекта")
    values_table: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = Field(default=None, description="Уникальное техническое имя объекта", alias="valuesTable")
    text_table: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = Field(default=None, description="Уникальное техническое имя объекта", alias="textTable")
    attributes_table: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = Field(default=None, description="Уникальное техническое имя объекта", alias="attributesTable")
    hierarchy_versions_table: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = Field(default=None, description="Уникальное техническое имя объекта", alias="hierarchyVersionsTable")
    hierarchy_text_versions_table: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = Field(default=None, description="Уникальное техническое имя объекта", alias="hierarchyTextVersionsTable")
    hierarchy_nodes_table: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = Field(default=None, description="Уникальное техническое имя объекта", alias="hierarchyNodesTable")
    hierarchy_text_nodes_table: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = Field(default=None, description="Уникальное техническое имя объекта", alias="hierarchyTextNodesTable")
    attributes_time_dependency: Optional[StrictBool] = Field(default=False, description="Зависимость атрибутов от времени", alias="attributesTimeDependency")
    pv_dictionary: Optional[PvDictionary] = Field(default=None, alias="pvDictionary")
    models: Optional[Annotated[List[ModelStatus], Field(max_length=1000)]] = Field(default=None, description="Массив имен моделей, к которым относится измерение со статусом обработки объекта в них")
    have_hierarchy: Optional[StrictBool] = Field(default=False, description="Наличие иерархии", alias="haveHierarchy")
    fbp: Optional[Annotated[List[Annotated[str, Field(min_length=0, strict=True, max_length=10)]], Field(max_length=1000)]] = None
    information_category: Optional[InformationCategory] = Field(default=None, alias="informationCategory")
    labels: Optional[Annotated[List[ObjectLabelsInner], Field(max_length=100)]] = Field(default=None, description="Тексты, которые описывают различные сущности системы на разных языках для   - признаков   - атрибутов признаков   - показателей   - хранилищ данных   - композитов   - ... ")
    precision: Optional[Annotated[int, Field(le=1333, strict=True, ge=1)]] = Field(default=None, description="Длина поля")
    type: Optional[DimensionKeyType] = None
    authorization_relevant: Optional[StrictBool] = Field(default=False, description="Релевантность проверке полномочий", alias="authorizationRelevant")
    texts_time_dependency: Optional[StrictBool] = Field(default=False, description="Зависимость текстов от времени", alias="textsTimeDependency")
    texts_language_dependency: Optional[StrictBool] = Field(default=False, description="Зависимость текстов от языка", alias="textsLanguageDependency")
    dimension_ref: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=32)]] = Field(default=None, description="Уникальное техническое имя объекта", alias="dimensionRef")
    value_texts: Optional[Annotated[List[ValueText], Field(max_length=10)]] = Field(default=None, alias="valueTexts")
    value_attributes: Optional[Annotated[List[DimensionAttribute], Field(max_length=1000)]] = Field(default=None, alias="valueAttributes")
    case_sensitive: Optional[StrictBool] = Field(default=False, description="Зависимость значений от регистра", alias="caseSensitive")
    data_access_method: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=255)]] = Field(default=None, description="Метод доступа к данным", alias="dataAccessMethod")
    business_key_representation: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=255)]] = Field(default=None, description="Отображение бизнес-ключа", alias="businessKeyRepresentation")
    is_virtual: Optional[StrictBool] = Field(default=False, description="Виртуальное измерение", alias="isVirtual")
    ai_prompt: Optional[AiPrompt] = Field(default=None, alias="aiPrompt")
    consistency: Optional[StrictBool] = Field(default=None, description="Консистентность объекта (одинаковое состояние объекта во всех моделях)")
    __properties: ClassVar[List[str]] = ["version", "updatedAt", "updatedBy", "status", "name", "valuesTable", "textTable", "attributesTable", "hierarchyVersionsTable", "hierarchyTextVersionsTable", "hierarchyNodesTable", "hierarchyTextNodesTable", "attributesTimeDependency", "pvDictionary", "models", "haveHierarchy", "fbp", "informationCategory", "labels", "precision", "type", "authorizationRelevant", "textsTimeDependency", "textsLanguageDependency", "dimensionRef", "valueTexts", "valueAttributes", "caseSensitive", "dataAccessMethod", "businessKeyRepresentation", "isVirtual", "aiPrompt", "consistency"]

    @field_validator('updated_at')
    def updated_at_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\n\t]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\n\t]+$/")
        return value

    @field_validator('updated_by')
    def updated_by_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\n\t]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\n\t]+$/")
        return value

    @field_validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9_]+$/")
        return value

    @field_validator('values_table')
    def values_table_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9_]+$/")
        return value

    @field_validator('text_table')
    def text_table_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9_]+$/")
        return value

    @field_validator('attributes_table')
    def attributes_table_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9_]+$/")
        return value

    @field_validator('hierarchy_versions_table')
    def hierarchy_versions_table_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9_]+$/")
        return value

    @field_validator('hierarchy_text_versions_table')
    def hierarchy_text_versions_table_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9_]+$/")
        return value

    @field_validator('hierarchy_nodes_table')
    def hierarchy_nodes_table_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9_]+$/")
        return value

    @field_validator('hierarchy_text_nodes_table')
    def hierarchy_text_nodes_table_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9_]+$/")
        return value

    @field_validator('dimension_ref')
    def dimension_ref_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9_]+$/")
        return value

    @field_validator('data_access_method')
    def data_access_method_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z0-9_]+$/")
        return value

    @field_validator('business_key_representation')
    def business_key_representation_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z0-9_]+$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Dimension from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of pv_dictionary
        if self.pv_dictionary:
            _dict['pvDictionary'] = self.pv_dictionary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in models (list)
        _items = []
        if self.models:
            for _item_models in self.models:
                if _item_models:
                    _items.append(_item_models.to_dict())
            _dict['models'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items = []
        if self.labels:
            for _item_labels in self.labels:
                if _item_labels:
                    _items.append(_item_labels.to_dict())
            _dict['labels'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in value_attributes (list)
        _items = []
        if self.value_attributes:
            for _item_value_attributes in self.value_attributes:
                if _item_value_attributes:
                    _items.append(_item_value_attributes.to_dict())
            _dict['valueAttributes'] = _items
        # override the default output from pydantic by calling `to_dict()` of ai_prompt
        if self.ai_prompt:
            _dict['aiPrompt'] = self.ai_prompt.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Dimension from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "version": obj.get("version"),
            "updatedAt": obj.get("updatedAt"),
            "updatedBy": obj.get("updatedBy"),
            "status": obj.get("status"),
            "name": obj.get("name"),
            "valuesTable": obj.get("valuesTable"),
            "textTable": obj.get("textTable"),
            "attributesTable": obj.get("attributesTable"),
            "hierarchyVersionsTable": obj.get("hierarchyVersionsTable"),
            "hierarchyTextVersionsTable": obj.get("hierarchyTextVersionsTable"),
            "hierarchyNodesTable": obj.get("hierarchyNodesTable"),
            "hierarchyTextNodesTable": obj.get("hierarchyTextNodesTable"),
            "attributesTimeDependency": obj.get("attributesTimeDependency") if obj.get("attributesTimeDependency") is not None else False,
            "pvDictionary": PvDictionary.from_dict(obj["pvDictionary"]) if obj.get("pvDictionary") is not None else None,
            "models": [ModelStatus.from_dict(_item) for _item in obj["models"]] if obj.get("models") is not None else None,
            "haveHierarchy": obj.get("haveHierarchy") if obj.get("haveHierarchy") is not None else False,
            "fbp": obj.get("fbp"),
            "informationCategory": obj.get("informationCategory"),
            "labels": [ObjectLabelsInner.from_dict(_item) for _item in obj["labels"]] if obj.get("labels") is not None else None,
            "precision": obj.get("precision"),
            "type": obj.get("type"),
            "authorizationRelevant": obj.get("authorizationRelevant") if obj.get("authorizationRelevant") is not None else False,
            "textsTimeDependency": obj.get("textsTimeDependency") if obj.get("textsTimeDependency") is not None else False,
            "textsLanguageDependency": obj.get("textsLanguageDependency") if obj.get("textsLanguageDependency") is not None else False,
            "dimensionRef": obj.get("dimensionRef"),
            "valueTexts": obj.get("valueTexts"),
            "valueAttributes": [DimensionAttribute.from_dict(_item) for _item in obj["valueAttributes"]] if obj.get("valueAttributes") is not None else None,
            "caseSensitive": obj.get("caseSensitive") if obj.get("caseSensitive") is not None else False,
            "dataAccessMethod": obj.get("dataAccessMethod"),
            "businessKeyRepresentation": obj.get("businessKeyRepresentation"),
            "isVirtual": obj.get("isVirtual") if obj.get("isVirtual") is not None else False,
            "aiPrompt": AiPrompt.from_dict(obj["aiPrompt"]) if obj.get("aiPrompt") is not None else None,
            "consistency": obj.get("consistency")
        })
        return _obj


