# coding: utf-8

"""
    V1 Semantic layer API

    Semantic layer API for EPMPlatform

    The version of the OpenAPI document: 1.0.0
    Contact: abakin.a.v@sberbank.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DimensionKeyType(str, Enum):
    """
    Технический тип данных поля для измерения
    """

    """
    allowed enum values
    """
    INTEGER = 'INTEGER'
    STRING = 'STRING'
    DATE = 'DATE'
    TIME = 'TIME'
    DATETIME = 'DATETIME'
    TIMESTAMP = 'TIMESTAMP'
    BOOLEAN = 'BOOLEAN'
    ARRAY_LEFT_SQUARE_BRACKET_STRING_RIGHT_SQUARE_BRACKET = 'ARRAY[STRING]'
    UUID = 'UUID'
    ARRAY_LEFT_SQUARE_BRACKET_INTEGER_RIGHT_SQUARE_BRACKET = 'ARRAY[INTEGER]'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DimensionKeyType from a JSON string"""
        return cls(json.loads(json_str))


