# coding: utf-8

"""
    V1 Semantic layer API

    Semantic layer API for EPMPlatform

    The version of the OpenAPI document: 1.0.0
    Contact: abakin.a.v@sberbank.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from src.integrations.modelling_tools_api.codegen.models.object_labels_inner import ObjectLabelsInner
from typing import Set
from typing_extensions import Self

class HierarchyEdit(BaseModel):
    """
    HierarchyEdit
    """ # noqa: E501
    labels: Optional[Annotated[List[ObjectLabelsInner], Field(max_length=100)]] = Field(default=None, description="Тексты, которые описывают различные сущности системы на разных языках для   - признаков   - атрибутов признаков   - показателей   - хранилищ данных   - композитов   - ... ")
    additional_dimensions: Optional[Annotated[List[Annotated[str, Field(min_length=1, strict=True, max_length=32)]], Field(max_length=1000)]] = Field(default=None, description="Дополнительные (не базовые) измерения иерархии", alias="additionalDimensions")
    default_hierarchy: Optional[StrictBool] = Field(default=False, description="Признак базовой иерархии для справочника.", alias="defaultHierarchy")
    is_versioned: Optional[StrictBool] = Field(default=False, description="Версионируемость", alias="isVersioned")
    is_timedependent: Optional[StrictBool] = Field(default=False, description="Зависимость от времени", alias="isTimedependent")
    time_dependency_type: Optional[Annotated[str, Field(strict=True, max_length=20)]] = Field(default=None, description="Тип зависимости от времени - WHOLE - зависит вся иерархия - NODE - только узлы ", alias="timeDependencyType")
    default_expansion: Optional[Annotated[int, Field(le=99, strict=True, ge=1)]] = Field(default=3, description="Начальный уровень развертки", alias="defaultExpansion")
    aggregation_type: Optional[Annotated[str, Field(strict=True, max_length=20)]] = Field(default='SUM', description="Тип агрегации: - 'NONE' - без агрегации, - 'SUM' - суммирование, - 'AVG' - расчет среднего значения ", alias="aggregationType")
    input_on_nodes: Optional[StrictBool] = Field(default=False, description="Разрешить ввод на узлы.", alias="inputOnNodes")
    __properties: ClassVar[List[str]] = ["labels", "additionalDimensions", "defaultHierarchy", "isVersioned", "isTimedependent", "timeDependencyType", "defaultExpansion", "aggregationType", "inputOnNodes"]

    @field_validator('time_dependency_type')
    def time_dependency_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['WHOLE', 'NODE']):
            raise ValueError("must be one of enum values ('WHOLE', 'NODE')")
        return value

    @field_validator('aggregation_type')
    def aggregation_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NONE', 'SUM', 'AVG']):
            raise ValueError("must be one of enum values ('NONE', 'SUM', 'AVG')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HierarchyEdit from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items = []
        if self.labels:
            for _item_labels in self.labels:
                if _item_labels:
                    _items.append(_item_labels.to_dict())
            _dict['labels'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HierarchyEdit from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "labels": [ObjectLabelsInner.from_dict(_item) for _item in obj["labels"]] if obj.get("labels") is not None else None,
            "additionalDimensions": obj.get("additionalDimensions"),
            "defaultHierarchy": obj.get("defaultHierarchy") if obj.get("defaultHierarchy") is not None else False,
            "isVersioned": obj.get("isVersioned") if obj.get("isVersioned") is not None else False,
            "isTimedependent": obj.get("isTimedependent") if obj.get("isTimedependent") is not None else False,
            "timeDependencyType": obj.get("timeDependencyType"),
            "defaultExpansion": obj.get("defaultExpansion") if obj.get("defaultExpansion") is not None else 3,
            "aggregationType": obj.get("aggregationType") if obj.get("aggregationType") is not None else 'SUM',
            "inputOnNodes": obj.get("inputOnNodes") if obj.get("inputOnNodes") is not None else False
        })
        return _obj


