# coding: utf-8

"""
    V1 Semantic layer API

    Semantic layer API for EPMPlatform

    The version of the OpenAPI document: 1.0.0
    Contact: abakin.a.v@sberbank.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from src.integrations.modelling_tools_api.codegen.models.aggregation_type import AggregationType
from src.integrations.modelling_tools_api.codegen.models.dimension_filter import DimensionFilter
from src.integrations.modelling_tools_api.codegen.models.measure_edit_unit_of_measure import MeasureEditUnitOfMeasure
from src.integrations.modelling_tools_api.codegen.models.measure_key_type import MeasureKeyType
from src.integrations.modelling_tools_api.codegen.models.object_labels_inner import ObjectLabelsInner
from typing import Set
from typing_extensions import Self

class MeasureCreate(BaseModel):
    """
    MeasureCreate
    """ # noqa: E501
    labels: Optional[Annotated[List[ObjectLabelsInner], Field(max_length=100)]] = Field(default=None, description="Тексты, которые описывают различные сущности системы на разных языках для   - признаков   - атрибутов признаков   - показателей   - хранилищ данных   - композитов   - ... ")
    measure_ref: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=32)]] = Field(default=None, description="Уникальное техническое имя объекта", alias="measureRef")
    type: Optional[MeasureKeyType] = None
    precision: Optional[Annotated[int, Field(le=34, strict=True, ge=1)]] = Field(default=0, description="При изменении только в сторону увеличения")
    scale: Optional[Annotated[int, Field(le=34, strict=True, ge=0)]] = Field(default=None, description="При изменении только в сторону увеличения, актуально для типа данных Decimal")
    authorization_relevant: Optional[StrictBool] = Field(default=False, description="authorization relevance", alias="authorizationRelevant")
    aggregation_type: Optional[AggregationType] = Field(default=None, alias="aggregationType")
    unit_of_measure: Optional[MeasureEditUnitOfMeasure] = Field(default=None, alias="unitOfMeasure")
    filter: Optional[Annotated[List[DimensionFilter], Field(max_length=100)]] = Field(default=None, description="Список уникальных значений dimension")
    name: Annotated[str, Field(min_length=1, strict=True, max_length=32)] = Field(description="Уникальное техническое имя объекта")
    __properties: ClassVar[List[str]] = ["labels", "measureRef", "type", "precision", "scale", "authorizationRelevant", "aggregationType", "unitOfMeasure", "filter", "name"]

    @field_validator('measure_ref')
    def measure_ref_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9_]+$/")
        return value

    @field_validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9_]+$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MeasureCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items = []
        if self.labels:
            for _item_labels in self.labels:
                if _item_labels:
                    _items.append(_item_labels.to_dict())
            _dict['labels'] = _items
        # override the default output from pydantic by calling `to_dict()` of unit_of_measure
        if self.unit_of_measure:
            _dict['unitOfMeasure'] = self.unit_of_measure.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in filter (list)
        _items = []
        if self.filter:
            for _item_filter in self.filter:
                if _item_filter:
                    _items.append(_item_filter.to_dict())
            _dict['filter'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MeasureCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "labels": [ObjectLabelsInner.from_dict(_item) for _item in obj["labels"]] if obj.get("labels") is not None else None,
            "measureRef": obj.get("measureRef"),
            "type": obj.get("type"),
            "precision": obj.get("precision") if obj.get("precision") is not None else 0,
            "scale": obj.get("scale"),
            "authorizationRelevant": obj.get("authorizationRelevant") if obj.get("authorizationRelevant") is not None else False,
            "aggregationType": obj.get("aggregationType"),
            "unitOfMeasure": MeasureEditUnitOfMeasure.from_dict(obj["unitOfMeasure"]) if obj.get("unitOfMeasure") is not None else None,
            "filter": [DimensionFilter.from_dict(_item) for _item in obj["filter"]] if obj.get("filter") is not None else None,
            "name": obj.get("name")
        })
        return _obj


