# coding: utf-8

"""
    V1 Semantic layer API

    Semantic layer API for EPMPlatform

    The version of the OpenAPI document: 1.0.0
    Contact: abakin.a.v@sberbank.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from src.integrations.modelling_tools_api.codegen.models.object_field_type_ref_object import ObjectFieldTypeRefObject
from typing import Set
from typing_extensions import Self

class ObjectFieldType(BaseModel):
    """
    Тип ссылочного поля
    """ # noqa: E501
    ref_object_type: Optional[StrictStr] = Field(default=None, description="Тип ссылочного объекта", alias="refObjectType")
    ref_object: Optional[ObjectFieldTypeRefObject] = Field(default=None, alias="refObject")
    __properties: ClassVar[List[str]] = ["refObjectType", "refObject"]

    @field_validator('ref_object_type')
    def ref_object_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ANYFIELD', 'DIMENSION', 'MEASURE']):
            raise ValueError("must be one of enum values ('ANYFIELD', 'DIMENSION', 'MEASURE')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ObjectFieldType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ref_object
        if self.ref_object:
            _dict['refObject'] = self.ref_object.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ObjectFieldType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "refObjectType": obj.get("refObjectType"),
            "refObject": ObjectFieldTypeRefObject.from_dict(obj["refObject"]) if obj.get("refObject") is not None else None
        })
        return _obj


