# coding: utf-8

"""
    V1 Semantic layer API

    Semantic layer API for EPMPlatform

    The version of the OpenAPI document: 1.0.0
    Contact: abakin.a.v@sberbank.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from src.integrations.modelling_tools_api.codegen.models.label_type import LabelType
from typing import Set
from typing_extensions import Self

class ObjectLabelsInner(BaseModel):
    """
    Зависимый от языка текст различной длины
    """ # noqa: E501
    language: Annotated[str, Field(strict=True, max_length=5)] = Field(description="Язык текста")
    type: LabelType
    text: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=255)]] = Field(default=None, description="Отображаемый текст")
    __properties: ClassVar[List[str]] = ["language", "type", "text"]

    @field_validator('language')
    def language_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-z]{2}-[a-z]{2}$", value):
            raise ValueError(r"must validate the regular expression /^[a-z]{2}-[a-z]{2}$/")
        return value

    @field_validator('text')
    def text_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\n\t]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\n\t]+$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ObjectLabelsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ObjectLabelsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "language": obj.get("language"),
            "type": obj.get("type"),
            "text": obj.get("text")
        })
        return _obj


