# coding: utf-8

"""
    V1 Semantic layer API

    Semantic layer API for EPMPlatform

    The version of the OpenAPI document: 1.0.0
    Contact: abakin.a.v@sberbank.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class Port(BaseModel):
    """
    Порт подключения к базе данных
    """ # noqa: E501
    port: Annotated[int, Field(le=65535, strict=True, ge=1)] = Field(description="Порт подключения")
    protocol: Annotated[str, Field(strict=True, max_length=30)] = Field(description="Протокол подключения")
    sql_dialect: Annotated[str, Field(strict=True, max_length=30)] = Field(description="SQL диалект порта", alias="sqlDialect")
    secured: StrictBool = Field(description="Подключение защищено")
    __properties: ClassVar[List[str]] = ["port", "protocol", "sqlDialect", "secured"]

    @field_validator('protocol')
    def protocol_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['CLICKHOUSE_HTTP', 'CLICKHOUSE_NATIVE', 'POSTGRESQL_V3']):
            raise ValueError("must be one of enum values ('CLICKHOUSE_HTTP', 'CLICKHOUSE_NATIVE', 'POSTGRESQL_V3')")
        return value

    @field_validator('sql_dialect')
    def sql_dialect_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['CLICKHOUSE', 'GREENPLUM', 'POSTGRESQL']):
            raise ValueError("must be one of enum values ('CLICKHOUSE', 'GREENPLUM', 'POSTGRESQL')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Port from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Port from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "port": obj.get("port"),
            "protocol": obj.get("protocol"),
            "sqlDialect": obj.get("sqlDialect"),
            "secured": obj.get("secured") if obj.get("secured") is not None else False
        })
        return _obj


