# coding: utf-8

"""
    V1 Semantic layer API

    Semantic layer API for EPMPlatform

    The version of the OpenAPI document: 1.0.0
    Contact: abakin.a.v@sberbank.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SemanticType(str, Enum):
    """
    Семантический тип поля    - описательное (признак)   - значения (показатель) 
    """

    """
    allowed enum values
    """
    DIMENSION = 'DIMENSION'
    MEASURE = 'MEASURE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SemanticType from a JSON string"""
        return cls(json.loads(json_str))


