# coding: utf-8

"""
    V1 Semantic layer API

    Semantic layer API for EPMPlatform

    The version of the OpenAPI document: 1.0.0
    Contact: abakin.a.v@sberbank.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from src.integrations.modelling_tools_api.codegen.models.values_dimension_response_texts_inner import ValuesDimensionResponseTextsInner
from typing import Set
from typing_extensions import Self

class ValuesDimensionResponse(BaseModel):
    """
    Вывод значений справочника
    """ # noqa: E501
    bk: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Значение бизнес-ключа")
    texts: Optional[Annotated[List[ValuesDimensionResponseTextsInner], Field(max_length=10000)]] = Field(default=None, description="Текстовые значения")
    __properties: ClassVar[List[str]] = ["bk", "texts"]

    @field_validator('bk')
    def bk_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\n\t]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\n\t]+$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ValuesDimensionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in texts (list)
        _items = []
        if self.texts:
            for _item_texts in self.texts:
                if _item_texts:
                    _items.append(_item_texts.to_dict())
            _dict['texts'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ValuesDimensionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bk": obj.get("bk"),
            "texts": [ValuesDimensionResponseTextsInner.from_dict(_item) for _item in obj["texts"]] if obj.get("texts") is not None else None
        })
        return _obj


