# coding: utf-8

"""
    V1 Semantic layer API

    Semantic layer API for EPMPlatform

    The version of the OpenAPI document: 1.0.0
    Contact: abakin.a.v@sberbank.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Set
from typing_extensions import Self

class ValuesDimensionResponseTextsInner(BaseModel):
    """
    ValuesDimensionResponseTextsInner
    """ # noqa: E501
    date_to: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Дата окончания текста", alias="dateTo")
    date_from: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Дата начала текста", alias="dateFrom")
    language: Optional[Annotated[str, Field(strict=True, max_length=5)]] = Field(default=None, description="Язык текста")
    txt_long: Optional[Annotated[str, Field(strict=True, max_length=1333)]] = Field(default=None, description="Длинный текст", alias="txtLong")
    txt_medium: Optional[Annotated[str, Field(strict=True, max_length=40)]] = Field(default=None, description="Средний текст", alias="txtMedium")
    txt_short: Optional[Annotated[str, Field(strict=True, max_length=20)]] = Field(default=None, description="Короткий текст", alias="txtShort")
    __properties: ClassVar[List[str]] = ["dateTo", "dateFrom", "language", "txtLong", "txtMedium", "txtShort"]

    @field_validator('date_to')
    def date_to_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\n\t]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\n\t]+$/")
        return value

    @field_validator('date_from')
    def date_from_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\n\t]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\n\t]+$/")
        return value

    @field_validator('language')
    def language_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\n\t]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\n\t]+$/")
        return value

    @field_validator('txt_long')
    def txt_long_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\n\t]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\n\t]+$/")
        return value

    @field_validator('txt_medium')
    def txt_medium_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\n\t]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\n\t]+$/")
        return value

    @field_validator('txt_short')
    def txt_short_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\n\t]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\n\t]+$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ValuesDimensionResponseTextsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ValuesDimensionResponseTextsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dateTo": obj.get("dateTo"),
            "dateFrom": obj.get("dateFrom"),
            "language": obj.get("language"),
            "txtLong": obj.get("txtLong"),
            "txtMedium": obj.get("txtMedium"),
            "txtShort": obj.get("txtShort")
        })
        return _obj


