# coding: utf-8

"""
    V1 Semantic layer API

    Semantic layer API for EPMPlatform

    The version of the OpenAPI document: 1.0.0
    Contact: abakin.a.v@sberbank.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from src.integrations.modelling_tools_api.codegen.models.values_filters_request_control_date_or_period import ValuesFiltersRequestControlDateOrPeriod
from typing import Set
from typing_extensions import Self

class ValuesFiltersRequest(BaseModel):
    """
    Фильтры
    """ # noqa: E501
    include_blocks: Optional[Annotated[List[StrictStr], Field(max_length=3)]] = Field(default=None, description="Выбор блока справочника - Бизнес-ключи / Тексты справочника / Атрибуты", alias="includeBlocks")
    control_date_or_period: Optional[ValuesFiltersRequestControlDateOrPeriod] = Field(default=None, alias="controlDateOrPeriod")
    __properties: ClassVar[List[str]] = ["includeBlocks", "controlDateOrPeriod"]

    @field_validator('include_blocks')
    def include_blocks_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['BKS', 'TEXTS', 'ATTRIBUTES']):
                raise ValueError("each list item must be one of ('BKS', 'TEXTS', 'ATTRIBUTES')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ValuesFiltersRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of control_date_or_period
        if self.control_date_or_period:
            _dict['controlDateOrPeriod'] = self.control_date_or_period.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ValuesFiltersRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "includeBlocks": obj.get("includeBlocks"),
            "controlDateOrPeriod": ValuesFiltersRequestControlDateOrPeriod.from_dict(obj["controlDateOrPeriod"]) if obj.get("controlDateOrPeriod") is not None else None
        })
        return _obj


